version: "2"

run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - unparam
    - prealloc
    - revive

output:
  formats:
    github-actions:
      path: stdout
