run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 10
  goconst:
    min-len: 3
    min-occurrences: 3
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/vnykmshr/goflow
  misspell:
    locale: US
  unparam:
    check-exported: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - structcheck
    - deadcode
    - gofmt
    - goimports
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - unparam
    - prealloc
    - exportloopref

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
    - path: examples/
      linters:
        - errcheck